### ISSUE TITLE
Making this repository public

### ISSUE THREAD

**Issue by iteles** [actnforchildren/mental_health_app#17]
As an organisation building a great product that is likely to change the lives of many young people
I would like to make this project open source
So that we can widen the reach of our funding and also benefit from security updates, contributions and improvements from the community who are interested in supporting Action for Children and/or mental health.

Before we started working together, we had agreed this would be an open source project.

### Tasks
+ [x] Speak to @actngareth about making the repo public
+ [ ] Book call to discuss Action for Children's IT department's questions
+ [ ] Hold call
+ [ ] Carry out agreed actions (to be detailed)
+ [ ] Make repository public

**Comment by actngareth** [comment]
Apologies on the delay, I was in training yesterday and this didn’t get picked up by my colleagues. The Repo should now be public.

Thanks,
Gareth

**Comment by iteles** [comment]
Excellent, repo is now public. Thanks everyone!
