### ISSUE TITLE
Sprint 1 demo plan

### ISSUE THREAD

**Issue by Cleop** [actnforchildren/mental_health_app#51]
**The demo flow goes as follows:**

- Login with a pin
- Log today's emotion
- Show calendar view
- Demonstrate logout

Demoing from @RobStallion's screen.

**Setup requirements:** 
- Setup with dummy data from seeds file for previous days emotions
- There is no data for today

**Tasks still to do:**

- [x] @SimonLab - deployment
- [x] @RobStallion - styling login page (perhaps use the tile logo for now as a placeholder before we get the decision on which logo to use)
- [x] @RobStallion - styling well done 'yes' 'no' buttons and spacing
- [x] @RobStallion - set up seeds file for dummy data
- [x] Either @RobStallion or @SimonLab - add emoji logo assets rather than text emojis https://github.com/actnforchildren/mental_health_app/issues/7

**Things to do but not for the demo:**
- [x] @RobStallion - ask comment about what logo should be used on the login page (same one as the tile?)
- [x] @RobStallion - let me know which assets are missing from invision so we can contact Harry
- [x] @RobStallion - Create issues on autoform repo for changing the copy of a button e.g. 'save' -> 'go' and also for displaying a text area not just a text input
- [x] @RobStallion - error messages for incorrect pin
